/**
 * @fileoverview gRPC-Web generated client stub for chatpb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.chatpb = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chatpb.ChatServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chatpb.ChatServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chatpb.HelloRequest,
 *   !proto.chatpb.HelloReply>}
 */
const methodDescriptor_ChatService_SayHello = new grpc.web.MethodDescriptor(
  '/chatpb.ChatService/SayHello',
  grpc.web.MethodType.UNARY,
  proto.chatpb.HelloRequest,
  proto.chatpb.HelloReply,
  /**
   * @param {!proto.chatpb.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chatpb.HelloReply.deserializeBinary
);


/**
 * @param {!proto.chatpb.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chatpb.HelloReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chatpb.HelloReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chatpb.ChatServiceClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chatpb.ChatService/SayHello',
      request,
      metadata || {},
      methodDescriptor_ChatService_SayHello,
      callback);
};


/**
 * @param {!proto.chatpb.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chatpb.HelloReply>}
 *     Promise that resolves to the response
 */
proto.chatpb.ChatServicePromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chatpb.ChatService/SayHello',
      request,
      metadata || {},
      methodDescriptor_ChatService_SayHello);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chatpb.HelloRequest,
 *   !proto.chatpb.HelloReply>}
 */
const methodDescriptor_ChatService_SayHelloAgain = new grpc.web.MethodDescriptor(
  '/chatpb.ChatService/SayHelloAgain',
  grpc.web.MethodType.UNARY,
  proto.chatpb.HelloRequest,
  proto.chatpb.HelloReply,
  /**
   * @param {!proto.chatpb.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chatpb.HelloReply.deserializeBinary
);


/**
 * @param {!proto.chatpb.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chatpb.HelloReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chatpb.HelloReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chatpb.ChatServiceClient.prototype.sayHelloAgain =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chatpb.ChatService/SayHelloAgain',
      request,
      metadata || {},
      methodDescriptor_ChatService_SayHelloAgain,
      callback);
};


/**
 * @param {!proto.chatpb.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chatpb.HelloReply>}
 *     Promise that resolves to the response
 */
proto.chatpb.ChatServicePromiseClient.prototype.sayHelloAgain =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chatpb.ChatService/SayHelloAgain',
      request,
      metadata || {},
      methodDescriptor_ChatService_SayHelloAgain);
};


module.exports = proto.chatpb;

